# Generated by Django 5.0.6 on 2024-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('K1', models.FloatField()),
                ('mark', models.IntegerField()),
                ('A1', models.IntegerField()),
                ('B1', models.IntegerField()),
                ('K2', models.FloatField()),
                ('mark1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
